name: update submodule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: update submodules
        run: git submodule update --remote --recursive
      - uses: sarisia/actions-commit@master
        id: commit
        with:
          message: 'update submodules'
      - name: kick image build workflow
        if: ${{ steps.commit.outputs.changed }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          workflow: build and publish container image
      - uses: sarisia/actions-status-discord@v1
        if: ${{ steps.commit.outputs.changed == true }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
